# Generated by Django 4.1.4 on 2022-12-10 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='benefit',
            table='benefits',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='company',
            table='companies',
        ),
        migrations.AlterModelTable(
            name='companybenefit',
            table='company_benefits',
        ),
        migrations.AlterModelTable(
            name='facility',
            table='facilities',
        ),
    ]
